/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaOnlyRouteImport } from './routes/spa-only'
import { Route as FullSsrRouteImport } from './routes/full-ssr'
import { Route as IndexRouteImport } from './routes/index'

const SpaOnlyRoute = SpaOnlyRouteImport.update({
  id: '/spa-only',
  path: '/spa-only',
  getParentRoute: () => rootRouteImport,
} as any)
const FullSsrRoute = FullSsrRouteImport.update({
  id: '/full-ssr',
  path: '/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/full-ssr': typeof FullSsrRoute
  '/spa-only': typeof SpaOnlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/full-ssr': typeof FullSsrRoute
  '/spa-only': typeof SpaOnlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/full-ssr': typeof FullSsrRoute
  '/spa-only': typeof SpaOnlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/full-ssr' | '/spa-only'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/full-ssr' | '/spa-only'
  id: '__root__' | '/' | '/full-ssr' | '/spa-only'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FullSsrRoute: typeof FullSsrRoute
  SpaOnlyRoute: typeof SpaOnlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spa-only': {
      id: '/spa-only'
      path: '/spa-only'
      fullPath: '/spa-only'
      preLoaderRoute: typeof SpaOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-ssr': {
      id: '/full-ssr'
      path: '/full-ssr'
      fullPath: '/full-ssr'
      preLoaderRoute: typeof FullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FullSsrRoute: FullSsrRoute,
  SpaOnlyRoute: SpaOnlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
